# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/hgfs/vmshare/code/IPGC_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/hgfs/vmshare/code/IPGC_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/hgfs/vmshare/code/IPGC_test/CMakeFiles /mnt/hgfs/vmshare/code/IPGC_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/hgfs/vmshare/code/IPGC_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/DecisionTree.o: src/DecisionTree.cpp.o

.PHONY : src/DecisionTree.o

# target to build an object file
src/DecisionTree.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DecisionTree.cpp.o
.PHONY : src/DecisionTree.cpp.o

src/DecisionTree.i: src/DecisionTree.cpp.i

.PHONY : src/DecisionTree.i

# target to preprocess a source file
src/DecisionTree.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DecisionTree.cpp.i
.PHONY : src/DecisionTree.cpp.i

src/DecisionTree.s: src/DecisionTree.cpp.s

.PHONY : src/DecisionTree.s

# target to generate assembly for a file
src/DecisionTree.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DecisionTree.cpp.s
.PHONY : src/DecisionTree.cpp.s

src/DecisionTreeNode.o: src/DecisionTreeNode.cpp.o

.PHONY : src/DecisionTreeNode.o

# target to build an object file
src/DecisionTreeNode.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DecisionTreeNode.cpp.o
.PHONY : src/DecisionTreeNode.cpp.o

src/DecisionTreeNode.i: src/DecisionTreeNode.cpp.i

.PHONY : src/DecisionTreeNode.i

# target to preprocess a source file
src/DecisionTreeNode.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DecisionTreeNode.cpp.i
.PHONY : src/DecisionTreeNode.cpp.i

src/DecisionTreeNode.s: src/DecisionTreeNode.cpp.s

.PHONY : src/DecisionTreeNode.s

# target to generate assembly for a file
src/DecisionTreeNode.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DecisionTreeNode.cpp.s
.PHONY : src/DecisionTreeNode.cpp.s

src/MultipleQuery.o: src/MultipleQuery.cpp.o

.PHONY : src/MultipleQuery.o

# target to build an object file
src/MultipleQuery.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MultipleQuery.cpp.o
.PHONY : src/MultipleQuery.cpp.o

src/MultipleQuery.i: src/MultipleQuery.cpp.i

.PHONY : src/MultipleQuery.i

# target to preprocess a source file
src/MultipleQuery.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MultipleQuery.cpp.i
.PHONY : src/MultipleQuery.cpp.i

src/MultipleQuery.s: src/MultipleQuery.cpp.s

.PHONY : src/MultipleQuery.s

# target to generate assembly for a file
src/MultipleQuery.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MultipleQuery.cpp.s
.PHONY : src/MultipleQuery.cpp.s

src/Object.o: src/Object.cpp.o

.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i

.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s

.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/PreProcess.o: src/PreProcess.cpp.o

.PHONY : src/PreProcess.o

# target to build an object file
src/PreProcess.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PreProcess.cpp.o
.PHONY : src/PreProcess.cpp.o

src/PreProcess.i: src/PreProcess.cpp.i

.PHONY : src/PreProcess.i

# target to preprocess a source file
src/PreProcess.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PreProcess.cpp.i
.PHONY : src/PreProcess.cpp.i

src/PreProcess.s: src/PreProcess.cpp.s

.PHONY : src/PreProcess.s

# target to generate assembly for a file
src/PreProcess.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PreProcess.cpp.s
.PHONY : src/PreProcess.cpp.s

src/Sensor.o: src/Sensor.cpp.o

.PHONY : src/Sensor.o

# target to build an object file
src/Sensor.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Sensor.cpp.o
.PHONY : src/Sensor.cpp.o

src/Sensor.i: src/Sensor.cpp.i

.PHONY : src/Sensor.i

# target to preprocess a source file
src/Sensor.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Sensor.cpp.i
.PHONY : src/Sensor.cpp.i

src/Sensor.s: src/Sensor.cpp.s

.PHONY : src/Sensor.s

# target to generate assembly for a file
src/Sensor.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Sensor.cpp.s
.PHONY : src/Sensor.cpp.s

src/SimpleNetwork.o: src/SimpleNetwork.cpp.o

.PHONY : src/SimpleNetwork.o

# target to build an object file
src/SimpleNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SimpleNetwork.cpp.o
.PHONY : src/SimpleNetwork.cpp.o

src/SimpleNetwork.i: src/SimpleNetwork.cpp.i

.PHONY : src/SimpleNetwork.i

# target to preprocess a source file
src/SimpleNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SimpleNetwork.cpp.i
.PHONY : src/SimpleNetwork.cpp.i

src/SimpleNetwork.s: src/SimpleNetwork.cpp.s

.PHONY : src/SimpleNetwork.s

# target to generate assembly for a file
src/SimpleNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SimpleNetwork.cpp.s
.PHONY : src/SimpleNetwork.cpp.s

src/Transmitter.o: src/Transmitter.cpp.o

.PHONY : src/Transmitter.o

# target to build an object file
src/Transmitter.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Transmitter.cpp.o
.PHONY : src/Transmitter.cpp.o

src/Transmitter.i: src/Transmitter.cpp.i

.PHONY : src/Transmitter.i

# target to preprocess a source file
src/Transmitter.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Transmitter.cpp.i
.PHONY : src/Transmitter.cpp.i

src/Transmitter.s: src/Transmitter.cpp.s

.PHONY : src/Transmitter.s

# target to generate assembly for a file
src/Transmitter.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Transmitter.cpp.s
.PHONY : src/Transmitter.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... src/DecisionTree.o"
	@echo "... src/DecisionTree.i"
	@echo "... src/DecisionTree.s"
	@echo "... src/DecisionTreeNode.o"
	@echo "... src/DecisionTreeNode.i"
	@echo "... src/DecisionTreeNode.s"
	@echo "... src/MultipleQuery.o"
	@echo "... src/MultipleQuery.i"
	@echo "... src/MultipleQuery.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/PreProcess.o"
	@echo "... src/PreProcess.i"
	@echo "... src/PreProcess.s"
	@echo "... src/Sensor.o"
	@echo "... src/Sensor.i"
	@echo "... src/Sensor.s"
	@echo "... src/SimpleNetwork.o"
	@echo "... src/SimpleNetwork.i"
	@echo "... src/SimpleNetwork.s"
	@echo "... src/Transmitter.o"
	@echo "... src/Transmitter.i"
	@echo "... src/Transmitter.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

